add massive random test, as proposed in #3

diff --git a/.github/workflows/random-test.yml b/.github/workflows/random-test.yml
--- a/.github/workflows/random-test.yml
+++ b/.github/workflows/random-test.yml
@@ -1,13 +1,20 @@
 # This workflow will install Python dependencies, run tests and lint with a variety of Python versions
 # For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions
 
-name: Run Test with PyTest and Codecov
+# NOTE that this workflow should run with numba installed, without which the tests will take a long time to run.
+
+name: Run Massive Random Test with PyTest
 
 on:
   push:
     branches: [ dev ]
   pull_request:
     branches: [ master ]
+
+env:
+  ARTIFACTS_DIR: ${{ github.workspace }}/artifacts-${{ github.run_number }}
+  RANDOM_DATA_AMOUNT: 10000
+  RANDOM_DATA_RANGE: 1000000
 
 jobs:
   build:
@@ -27,15 +34,28 @@ jobs:
       run: |
         python -m pip install --upgrade pip setuptools wheel
         python -m pip install -r requirements.txt
-        python -m pip install pytest pytest-xdist pytest-cov # Testing packages
+        python -m pip install pytest pytest-xdist # Testing packages
         python -m pip uninstall diff-binom-confint --yes # Remove if already installed 
         python setup.py install_egg_info # Workaround https://github.com/pypa/pip/issues/4537
         python -m pip install -e .[dev]
         python -m pip freeze
-    - name: Run test with pytest and collect coverage
+    - name: Create artifacts directory if not exists
       run: |
-        pytest --cov=diff_binom_confint --ignore=test/test_random.py -v test
-        python -m pip uninstall numba --yes
-        pytest --cov=diff_binom_confint --ignore=test/test_random.py -v test
-    - name: Upload coverage to Codecov
-      uses: codecov/codecov-action@v3
+        mkdir -p $ARTIFACTS_DIR
+        # clear artifacts directory if exists
+        rm -rf $ARTIFACTS_DIR/*
+    - name: Run massive random test
+      run: |
+        pytest -v test/test_random.py
+    - name: Fail if artifacts directory is not empty
+      run: |
+        if [ "$(ls -A $ARTIFACTS_DIR)" ]; then
+          echo "Artifacts directory is not empty."
+          echo "Errors found in massive random test."
+          exit 1
+        fi
+    - name: Upload artifacts
+      uses: actions/upload-artifact@v2
+      with:
+        name: artifacts-${{ github.run_number }}
+        path: $ARTIFACTS_DIR
