enhance the random-test action

diff --git a/.github/workflows/random-test.yml b/.github/workflows/random-test.yml
--- a/.github/workflows/random-test.yml
+++ b/.github/workflows/random-test.yml
@@ -50,16 +50,23 @@ jobs:
     - name: Run massive random test
       run: |
         pytest -v test/test_random.py
+    - name: Check if artifacts directory is empty
+      id: check_artifacts_empty
+      run: |
+        if [ "$(ls -A $ARTIFACTS_DIR)" ]; then
+          echo "Artifacts directory is not empty."
+          echo "Errors found in massive random test."
+          echo "is_empty=false" >> "$GITHUB_OUTPUT"
+        else
+          echo "is_empty=true" >> "$GITHUB_OUTPUT"
+        fi
     - name: Upload artifacts if artifacts directory is not empty
-      # if : [ "$(ls -A $ARTIFACTS_DIR)" ]
+      if : ${{ steps.check_artifacts_empty.outputs.is_empty == 'false' }}
       uses: actions/upload-artifact@v3
       with:
         name: artifacts-${{ github.run_number }}
         path: $ARTIFACTS_DIR
     - name: Fail if artifacts directory is not empty
+      if : ${{ steps.check_artifacts_empty.outputs.is_empty == 'false' }}
       run: |
-        if [ "$(ls -A $ARTIFACTS_DIR)" ]; then
-          echo "Artifacts directory is not empty."
-          echo "Errors found in massive random test."
-          exit 1
-        fi
+        exit 1
